modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "moreprocessors"
version = "${version}"
displayName = "More Structure Processors"
authors = "Joseph T. McQuigg"
description = '''
Adds more structure processors for Developers to use in Mods or Datapacks
'''
#logoFile = ""

[[dependencies.moreprocessors]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moreprocessors]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
