modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "compatprocessors"
version = "${version}"
displayName = "Compatibility Structure Processors"
authors = "Joseph T. McQuigg"
description = '''
'''
#logoFile = ""

[[dependencies.compatprocessors]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.compatprocessors]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
