modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/JT122406/MoreStructureProcessors/issues"
license = "All Rights Reserved"

[[mods]]
modId = "moreprocessors"
version = "${version}"
displayName = "More Structure Processors"
authors = "Joseph T. McQuigg"
description = '''
Adds more structure processors for Developers to use in Mods or Datapacks
'''
logoFile = "icon.png"

[[dependencies.moreprocessors]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moreprocessors]]
modId = "minecraft"
type ="required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
